### ISSUE TITLE
можно также использовать переменную number (не number1)

### ISSUE THREAD

**Issue by tallinn-learning** [Yaroslav3390/homework04#1]
https://github.com/Yaroslav3390/homework04/blob/f663f0f91e4799727e15ebb27d428b9b33895299/src/NumberManipulator.java#LL6C40-L6C47

**Comment by Yaroslav3390** [comment]
Тогда у меня она красным подсвечиваться, не пойму

**Comment by tallinn-learning** [comment]
пришлите в чат пример пожалуйста
